CREATE TABLE users(
    user_id INT PRIMARY KEY AUTO_INCREMENT,

    name VARCHAR(60) NOT NULL,

    email VARCHAR(100) UNIQUE NOT NULL,

    password VARCHAR(255) NOT NULL,

    address VARCHAR(400),

    role ENUM('ADMIN','USER','OWNER') NOT NULL,

    is_active BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

    deleted_at TIMESTAMP NULL
);

CREATE TABLE stores(
    store_id INT PRIMARY KEY AUTO_INCREMENT,

    name VARCHAR(100) NOT NULL,

    email VARCHAR(100) UNIQUE NOT NULL,

    address VARCHAR(400),

    owner_id INT NOT NULL,

    is_active BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

    deleted_at TIMESTAMP NULL,

    FOREIGN KEY(owner_id)
    REFERENCES users(user_id)
);

CREATE TABLE ratings(
    rating_id INT PRIMARY KEY AUTO_INCREMENT,

    user_id INT NOT NULL,

    store_id INT NOT NULL,

    rating INT NOT NULL CHECK(rating BETWEEN 1 AND 5),

    is_active BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

    deleted_at TIMESTAMP NULL,

    FOREIGN KEY(user_id)
    REFERENCES users(user_id),

    FOREIGN KEY(store_id)
    REFERENCES stores(store_id),

    UNIQUE(user_id, store_id)
);